<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="table-wrapper reviews">
        <table class="data table table-reviews" id="my-reviews-table">
            <div class="block-title"><strong><?= $block->escapeHtml(__('My Reviews')) ?></strong></div>
            <thead>
                <tr>
                    <th scope="col" class="col item"><?= $block->escapeHtml(__('Reviewed Products')) ?></th>
                    <th scope="col" class="col summary"><?= $block->escapeHtml(__('Rating')) ?></th>
                    <th scope="col" class="col description"><?= $block->escapeHtml(__('Review')) ?></th>
                    <th scope="col" class="col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getReviews() as $_review): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item">
                        <strong class="product-name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_review)) ?>"><?= $block->escapeHtml($_review->getName()) ?></a>
                        </strong>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Rating')) ?>" class="col summary">
                    <?php if ($_review->getSum()): ?>
                        <?php $percent=((int)$_review->getSum() / (int)$_review->getCount()) ?>
                    <?php else: ?>
                        <?php $percent=0 ?>
                    <?php endif; ?>
                        <div class="rating-summary">
                            <div class="rating-result" title="<?= $percent ?>%">
                                <meta itemprop="worstRating" content="1">
                                <meta itemprop="bestRating" content="100">
                                <meta itemprop="ratingValue" content="<?= $percent ?>">
                                <div class="rating-result__stars">
                                    <?php
                                    for($i = 0; $i < 5; $i++){
                                        echo '<span class="icon-star"></span>';
                                    } ?>
                                </div>

                                <div class="rating-result__text">
                                    <div style="width:<?= $percent ?>%">
                                        <?php
                                        for($i = 0; $i < 5; $i++){
                                            echo '<span class="icon-star"></span>';
                                        } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Review')) ?>" class="col description">
                        <?= $this->helper('Magento\Review\Helper\Data')->getDetailHtml($_review->getDetail()) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getReviewUrl($_review)) ?>" class="action more">
                            <span><?= $block->escapeHtml(__('View Details')) ?></span>
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="block-title"><strong><?= $block->escapeHtml(__('My Reviews')) ?></strong></div>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no reviews.')) ?></span></div>
<?php endif; ?>

