<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <ul class="items pages-items" aria-labelledby="paging-label">
                <li class="item pages-item-previous">
                    <?php if (!$block->isFirstPage()): ?>
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> previous" href="<?php /* @escapeNotVerified */ echo $block->getPreviousPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
<!--                        <span>--><?//= /* @escapeNotVerified */ __('Page') ?><!--</span>-->
                        <span class="label"><?php /* @escapeNotVerified */ echo __('') ?></span>
                    </a>
                    <?php else: ?>
                        <span class="label dimmed"><?= /* @escapeNotVerified */ __('') ?></span>
                    <?php endif;?>
                </li>


            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?php /* @escapeNotVerified */ echo $block->getFirstPageUrl() ?>">
                        <span class="label"><?php /* @escapeNotVerified */ // echo __('') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php /* @escapeNotVerified */ echo $block->getPreviousJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?php /* @escapeNotVerified */ // echo __('') ?></span>
                            <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($_page) ?>" class="page">
                            <span class="label"><?php /* @escapeNotVerified */ // echo __('') ?></span>
                            <span><?php /* @escapeNotVerified */ echo $_page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php /* @escapeNotVerified */ echo $block->getNextJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
              <li class="item">
                  <a class="page last" href="<?php /* @escapeNotVerified */ echo $block->getLastPageUrl() ?>">
<!--                      <span class="label">--><?php ///* @escapeNotVerified */ echo __('Last') ?><!--</span>-->
                      <span><?php /* @escapeNotVerified */ echo $block->getLastPageNum() ?></span>
                  </a>
              </li>
            <?php endif;?>

                <li class="item pages-item-next">
                    <?php if (!$block->isLastPage()): ?>
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php /* @escapeNotVerified */ echo $text ? 'link ' : 'action '?> next" href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                        <span class="label"><?= /* @escapeNotVerified */ __('') ?></span>
<!--                        <span>--><?//= /* @escapeNotVerified */ $text ? $text : __('Next') ?><!--</span>-->
                    </a>
                    <?php else: ?>
                        <span class="label dimmed"><?= /* @escapeNotVerified */ __('') ?></span>
                    <?php endif;?>
                </li>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
